export const FONTS = [
    { value: 'PT Serif', label: 'PT Serif' },
    { value: 'Arvo', label: 'Arvo' },
    { value: 'Bitter', label: 'Bitter' },
    { value: 'Cardo', label: 'Cardo' },
    { value: 'Domine', label: 'Domine' },
    { value: 'Old Standard TT', label: 'Old Standard TT' },
    { value: 'Varela Round', label:'Varela Round' },
    { value: 'Chivo', label: 'Chivo' },
    { value: 'Roboto', label: 'Roboto' },
    { value: 'Roboto Slab', label: 'Roboto Slab' },
    { value: 'Crimson Text', label: 'Crimson Text' },
    { value: 'Libre Baskerville', label: 'Libre Baskerville' },
    { value: 'Montserrat', label:'Montserrat' },
    { value: 'Archivo Narrow', label: 'Archivo Narrow' },
    { value: 'Lato', label: 'Lato' },
    { value: 'Anonymous Pro', label: 'Anonymous Pro' },
    { value: 'Merriweather', label: 'Merriweather' },
    { value: 'Neuton', label:'Neuton' },
    { value: 'Open Sans', label: 'Open Sans' },
    { value: 'Poppins', label: 'Poppins' },
    { value: 'Lora', label: 'Lora' },
    { value: 'Karla', label: 'Karla' },
    { value: 'Source Sans Pro', label: 'Source Sans Pro' },
    { value: 'Inconsolata', label: 'Inconsolata' },
    { value: 'Playfair Display', label: 'Playfair Display' },
    { value: 'Work Sans', label: 'Work Sans' },
    { value: 'Alegreya', label: 'Alegreya' },
    { value: 'Alegreya Sans', label: 'Alegreya Sans' },
    { value: 'Fira Sans', label: 'Fira Sans' }
];
